DB:
    # prod conn string: Driver={ODBC Driver 17 for SQL Server};Server=10.160.20.65,51261;Database=dw_motrpac;UID={!db_user_name!};PWD={!db_user_pwd!}
    # New prod conn string: Driver={ODBC Driver 17 for SQL Server};Server=10.9.10.59,59105;Database=dw_motrpac;UID={!db_user_name!};PWD={!db_user_pwd!}
    # DB connection string
    mdb_conn_str: Driver={ODBC Driver 17 for SQL Server};Server=10.9.10.59,59105;Database=dw_motrpac;UID={!db_user_name!};PWD={!db_user_pwd!}
    db_user_name_pl_holder: "{!db_user_name!}"
    db_user_pwd_pl_holder: "{!db_user_pwd!}"
    env_db_user_name: APP_DB_USER_NAME
    env_db_user_pwd: APP_DB_USER_PWD
    # name of the stored proc to be used to load samples to DB
    mdb_sql_proc_load_sample: exec usp_load_single_sample @study_id = {study_id}, @sample_id ='{sample_id}', @json ='{smpl_json}', @dict_json='{dict_json}', @dict_path='{dict_path}', @data_source='{data_source}', @dict_update={dict_update}, @samlpe_update={samlpe_update}

    # name of field templates for updating of stored procedure parameters (specified in "mdb_sql_proc_load_sample")
    fld_tmpl_study_id: '{study_id}'
    fld_tmpl_sample_id: '{sample_id}'
    fld_tmpl_row_json: '{smpl_json}'
    fld_tmpl_dict_json: '{dict_json}'
    fld_tmpl_dict_path: '{dict_path}'
    fld_tmpl_filepath: '{data_source}'
    fld_tmpl_dict_update: '{dict_update}'
    fld_tmpl_samlpe_update: '{samlpe_update}'

Location:
    # path to the folder where all data files are located
    #local path
    data_folder: /mnt/researchsan02a/Metadata_Processing
    # production path
    # data_folder: J:\Metadata_Processing

    ignore_files:
        - ".DS_Store"
        - "study.cfg.yaml"
        - "Thumbs.db"

    #name of the folder where all logs files will be stored
    log_folder_name: logs
    processed_folder_name: processed
    processed_file_copies_max_number: -1 #number of copies of file allowed; -1 - stands for unlimited number of copies, if ommitted the default value from GlobalConst will be used

Logging:
    #main log - log created by the main application
    #file log - log created for each processed file

    #defines log levels to be used for "main" and "file" logs. Usual values are INFO and DEBUG
    main_log_level: INFO  # DEBUG
    file_log_level: INFO

    #name for the each type of log (moved to global_const.py)
    #main_log_name: main_log
    #file_log_name: file_processing_log

Email:
    #default settings for sending emails
    smtp_server: smtp.mssm.edu
    smtp_server_port: 25
    default_from_email: stas.rirak@mssm.edu
    sent_to_emails: stasrirak.ms@gmail.com,german.nudelman@gmail.com
    send_emails: True # expected values: True, False

Validate:
    # list of environment variable required to be set for a current user in order to run the application
    environment_variables:
        default: # default list of variables required for all runs
            - APP_DB_USER_NAME
            - APP_DB_USER_PWD
        redcap: # list of variables required for RedCap run
            - REDCAP_HCW_TOKEN

API_process_configs:
    - api_redcap_hcw_metadata_config.yaml
    # - api_redcap_hcw_metadata_config.yaml # duplicated entry for testing only
